/**
 * OpenClaw Pincers theme catalog.
 * Each theme maps CSS custom properties applied to <html> at runtime.
 */

export interface ThemeDef {
  id: string;
  name: string;
  blurb: string;
  dark: boolean;
  vars: Record<string, string>;
}

/** Token reference (kept in sync with src/app.css :root defaults):
 *  --bg          app background, editors, inputs
 *  --bg-panel    rail / sidebar background
 *  --bg-card     cards, message bubbles (assistant)
 *  --bg-hover    row hover
 *  --bg-active   active rows, chips
 *  --bg-msg      assistant message bubble alt
 *  --border      hairlines
 *  --border2     card borders
 *  --border-input input borders
 *  --text        primary text
 *  --text2..5    progressively dimmer text
 *  --muted       captions, timestamps
 *  --accent      primary brand color (Pincers pink)
 *  --accent2     gradient partner
 *  --success / --success-border / --success-text
 *  --danger / --danger-text
 *  --warning / --warning-border / --warning-text
 *  --mono        monospace/data accent (green)
 *  --bubble-user user chat bubble background
 */

export const THEMES: ThemeDef[] = [
  {
    id: "grid",
    name: "Grid Dark",
    blurb: "The default. Neon on asphalt.",
    dark: true,
    vars: {}, // :root defaults
  },
  {
    id: "synthwave",
    name: "Synthwave",
    blurb: "Hot pink sunsets, cyan horizons.",
    dark: true,
    vars: {
      "--bg": "#160a2e",
      "--bg-panel": "#1d0f3a",
      "--bg-card": "#221244",
      "--bg-hover": "#2a1854",
      "--bg-active": "#322065",
      "--bg-msg": "#241449",
      "--border": "#32205c",
      "--border2": "#3d266e",
      "--border-input": "#4a2f85",
      "--text": "#f8eaff",
      "--text2": "#dcc8f5",
      "--text3": "#bda3e0",
      "--text4": "#9f85c8",
      "--text5": "#8369ab",
      "--muted": "#655085",
      "--accent": "#ff2e88",
      "--accent2": "#00e5ff",
      "--success": "#2ee6a8",
      "--success-border": "#1d7a5c",
      "--success-text": "#7ff5cd",
      "--danger": "#c23a5a",
      "--danger-text": "#ff9ab8",
      "--warning": "#ffd166",
      "--warning-border": "#7a6420",
      "--warning-text": "#f5e3ae",
      "--mono": "#7ef7d4",
      "--bubble-user": "#3d2a8a",
    },
  },
  {
    id: "synthwave84",
    name: "Synthwave ’84",
    blurb: "Chrome, cassette sunsets, VHS static.",
    dark: true,
    vars: {
      "--bg": "#12082b",
      "--bg-panel": "#180d38",
      "--bg-card": "#1e1145",
      "--bg-hover": "#261655",
      "--bg-active": "#2e1c68",
      "--bg-msg": "#201349",
      "--border": "#2c1a58",
      "--border2": "#38216c",
      "--border-input": "#452b82",
      "--text": "#e8ecff",
      "--text2": "#c9d2f2",
      "--text3": "#a8b4dd",
      "--text4": "#8b97c5",
      "--text5": "#707ca8",
      "--muted": "#585f85",
      "--accent": "#ff9e3d",
      "--accent2": "#ff3864",
      "--success": "#35e0b0",
      "--success-border": "#1f7a5e",
      "--success-text": "#8af0cd",
      "--danger": "#c23a4e",
      "--danger-text": "var(--danger-text)",
      "--warning": "var(--warning)",
      "--warning-border": "#7a5f1f",
      "--warning-text": "#f0e0b0",
      "--mono": "#4de8c2",
      "--bubble-user": "#35307a",
    },
  },
  {
    id: "light",
    name: "Light",
    blurb: "Daylight on the grid.",
    dark: false,
    vars: {
      "--bg": "#f2f3f7",
      "--bg-panel": "#e8eaf1",
      "--bg-card": "#ffffff",
      "--bg-hover": "#e2e5ee",
      "--bg-active": "#d8dcea",
      "--bg-msg": "#eef0f6",
      "--border": "#d4d8e4",
      "--border2": "#c8cddd",
      "--border-input": "#b8bfd4",
      "--text": "#1c2330",
      "--text2": "#2e3748",
      "--text3": "#465062",
      "--text4": "#5c6678",
      "--text5": "#748099",
      "--muted": "#8a93a8",
      "--accent": "#d61f8c",
      "--accent2": "#6a4de0",
      "--success": "#14805a",
      "--success-border": "#a8d8c4",
      "--success-text": "#0f6b4a",
      "--danger": "#c22840",
      "--danger-text": "#c22840",
      "--warning": "#a8761a",
      "--warning-border": "#e0d0a8",
      "--warning-text": "#7a5a12",
      "--mono": "#0f7a52",
      "--bubble-user": "#d5defc",
    },
  },
  {
    id: "classic-linux",
    name: "Classic Linux",
    blurb: "CDE grays, Motif vibes, 1998 called.",
    dark: false,
    vars: {
      "--bg": "#d6d2c8",
      "--bg-panel": "#c8c4ba",
      "--bg-card": "#e2ded4",
      "--bg-hover": "#ccc8be",
      "--bg-active": "#c0bcb2",
      "--bg-msg": "#dedad0",
      "--border": "#a8a498",
      "--border2": "#98948a",
      "--border-input": "#8a8578",
      "--text": "#1a1a1a",
      "--text2": "#2a2a2a",
      "--text3": "#3d3d3a",
      "--text4": "#4f4f4a",
      "--text5": "#62625c",
      "--muted": "#76766e",
      "--accent": "#2b5cab",
      "--accent2": "#1d3f7a",
      "--success": "#2a6b3a",
      "--success-border": "#8aa890",
      "--success-text": "#245c32",
      "--danger": "#a02828",
      "--danger-text": "#a02828",
      "--warning": "#7a5c10",
      "--warning-border": "#b0a070",
      "--warning-text": "#66500e",
      "--mono": "#1d5c32",
      "--bubble-user": "#b8c4dc",
    },
  },
  {
    id: "deep-claw",
    name: "Deep Claw",
    blurb: "Abyssal. Bioluminescence only.",
    dark: true,
    vars: {
      "--bg": "#030b14",
      "--bg-panel": "#051120",
      "--bg-card": "#071827",
      "--bg-hover": "#0a2032",
      "--bg-active": "#0d2840",
      "--bg-msg": "#081a2b",
      "--border": "#0e2438",
      "--border2": "#123048",
      "--border-input": "#174058",
      "--text": "#c8ecf7",
      "--text2": "#a5d4e5",
      "--text3": "#82b5cb",
      "--text4": "#6497b0",
      "--text5": "#4c7a92",
      "--muted": "#3a5f75",
      "--accent": "#22d3ee",
      "--accent2": "#0e7490",
      "--success": "#2dd4a0",
      "--success-border": "#14634c",
      "--success-text": "#6fe8c2",
      "--danger": "#c24545",
      "--danger-text": "#ff9a9a",
      "--warning": "#eab308",
      "--warning-border": "#5c4a10",
      "--warning-text": "#f0dc90",
      "--mono": "#5eead4",
      "--bubble-user": "#0c3a52",
    },
  },
  {
    id: "molt",
    name: "Molt",
    blurb: "Fresh shell, soft sand, new exoskeleton.",
    dark: false,
    vars: {
      "--bg": "#f2ece1",
      "--bg-panel": "#e9e1d3",
      "--bg-card": "#faf6ec",
      "--bg-hover": "#e0d7c6",
      "--bg-active": "#d5cab5",
      "--bg-msg": "#ece4d3",
      "--border": "#d5cab5",
      "--border2": "#c7b9a2",
      "--border-input": "#b3a48c",
      "--text": "#3d3329",
      "--text2": "#4f4438",
      "--text3": "#63564a",
      "--text4": "#79695c",
      "--text5": "#8f7f70",
      "--muted": "#a2937f",
      "--accent": "#c96f4a",
      "--accent2": "#a04a2e",
      "--success": "#4a7a3a",
      "--success-border": "#b0c49a",
      "--success-text": "#3e6632",
      "--danger": "#b03a2e",
      "--danger-text": "#b03a2e",
      "--warning": "#a8761a",
      "--warning-border": "#d8c49a",
      "--warning-text": "#7a5a12",
      "--mono": "#3a6b4a",
      "--bubble-user": "#e0cbb0",
    },
  },
  {
    id: "krill-royale",
    name: "Krill Royale",
    blurb: "Tiny crustacean, massive crown energy.",
    dark: true,
    vars: {
      "--bg": "#1c0a12",
      "--bg-panel": "#240d17",
      "--bg-card": "#2c101d",
      "--bg-hover": "#361424",
      "--bg-active": "#42182c",
      "--bg-msg": "#2e121f",
      "--border": "#3d1628",
      "--border2": "#4c1b32",
      "--border-input": "#5e2340",
      "--text": "#fbe8ef",
      "--text2": "#eecdd9",
      "--text3": "#d4acbc",
      "--text4": "#b78da0",
      "--text5": "#977085",
      "--muted": "#77586a",
      "--accent": "#ff6b9d",
      "--accent2": "#ffd166",
      "--success": "var(--success)",
      "--success-border": "#256b48",
      "--success-text": "var(--success-text)",
      "--danger": "#c23a4e",
      "--danger-text": "var(--danger-text)",
      "--warning": "#ffd166",
      "--warning-border": "var(--warning-border)",
      "--warning-text": "#f0dcae",
      "--mono": "#8af0cd",
      "--bubble-user": "#54203a",
    },
  },
  {
    id: "pinch-harmonix",
    name: "Pinch Harmonix",
    blurb: "VU meters pegged. Lime + magenta on stage black.",
    dark: true,
    vars: {
      "--bg": "#0a0a0f",
      "--bg-panel": "#101016",
      "--bg-card": "#14141c",
      "--bg-hover": "#1a1a24",
      "--bg-active": "#20202e",
      "--bg-msg": "#16161e",
      "--border": "#20202c",
      "--border2": "#282836",
      "--border-input": "#323242",
      "--text": "#e8f0e8",
      "--text2": "#c8d8c8",
      "--text3": "#a4b8a8",
      "--text4": "#84988c",
      "--text5": "#6a7c72",
      "--muted": "#546058",
      "--accent": "#a3ff12",
      "--accent2": "#ff2ed4",
      "--success": "#4ae88a",
      "--success-border": "#226b42",
      "--success-text": "#8af0b8",
      "--danger": "#d43a4e",
      "--danger-text": "#ff9aa8",
      "--warning": "#ffc94d",
      "--warning-border": "#6b571c",
      "--warning-text": "#f0e0ae",
      "--mono": "#a3ff12",
      "--bubble-user": "#2a3a14",
    },
  },
  {
    id: "clawde-monet",
    name: "Clawde Monet",
    blurb: "Water lilies at Giverny. Impressionist pastel.",
    dark: false,
    vars: {
      "--bg": "#e9efea",
      "--bg-panel": "#dfe8e2",
      "--bg-card": "#f4f8f3",
      "--bg-hover": "#d2dfd6",
      "--bg-active": "#c4d4ca",
      "--bg-msg": "#e2ece4",
      "--border": "#c2d2c6",
      "--border2": "#b0c2b6",
      "--border-input": "#9cb0a2",
      "--text": "#2c3a34",
      "--text2": "#3d4c44",
      "--text3": "#505f57",
      "--text4": "#64736b",
      "--text5": "#7a8880",
      "--muted": "#909d95",
      "--accent": "#7a6fb8",
      "--accent2": "#d4749c",
      "--success": "#4a8a5a",
      "--success-border": "#a8c8b0",
      "--success-text": "#3e744c",
      "--danger": "#b84a52",
      "--danger-text": "#b84a52",
      "--warning": "#a8842a",
      "--warning-border": "#d8cca0",
      "--warning-text": "#7a641e",
      "--mono": "#3d7a5c",
      "--bubble-user": "#cdc8e8",
    },
  },
  {
    id: "carapace-noir",
    name: "Carapace Noir",
    blurb: "Film noir. One red dress in a grayscale world.",
    dark: true,
    vars: {
      "--bg": "#0c0c0c",
      "--bg-panel": "#121212",
      "--bg-card": "#181818",
      "--bg-hover": "#1e1e1e",
      "--bg-active": "#262626",
      "--bg-msg": "#1a1a1a",
      "--border": "#242424",
      "--border2": "#2e2e2e",
      "--border-input": "#3a3a3a",
      "--text": "#e8e8e8",
      "--text2": "#c8c8c8",
      "--text3": "#a4a4a4",
      "--text4": "#888888",
      "--text5": "#6e6e6e",
      "--muted": "#565656",
      "--accent": "#e02424",
      "--accent2": "#8a8a8a",
      "--success": "#4ac26b",
      "--success-border": "#2a5c3a",
      "--success-text": "#7fd698",
      "--danger": "#c23a3a",
      "--danger-text": "#ff9a9a",
      "--warning": "#d4b04d",
      "--warning-border": "#5c4c1c",
      "--warning-text": "#e8d8a0",
      "--mono": "#c8c8c8",
      "--bubble-user": "#333333",
    },
  },
  {
    id: "lobster-quadrille",
    name: "The Lobster Quadrille",
    blurb: "\"Will you, won't you join the dance?\" Undersea ballroom.",
    dark: true,
    vars: {
      "--bg": "#081a1c",
      "--bg-panel": "#0b2224",
      "--bg-card": "#0e2a2c",
      "--bg-hover": "#123336",
      "--bg-active": "#173e42",
      "--bg-msg": "#102e30",
      "--border": "#163a3e",
      "--border2": "#1c484c",
      "--border-input": "#24585e",
      "--text": "#f0ead0",
      "--text2": "#d8d0b4",
      "--text3": "#bcb298",
      "--text4": "#9c9480",
      "--text5": "#807a68",
      "--muted": "#625e50",
      "--accent": "#e8b64d",
      "--accent2": "#2ec4b6",
      "--success": "#3fd8a0",
      "--success-border": "#1f6b50",
      "--success-text": "#86e8c2",
      "--danger": "#d44848",
      "--danger-text": "#ffa0a0",
      "--warning": "#e8b64d",
      "--warning-border": "#6b551c",
      "--warning-text": "#f0e0ae",
      "--mono": "#7ee8d8",
      "--bubble-user": "#144a4e",
    },
  },
  {
    id: "barnacle",
    name: "Barnacle",
    blurb: "Stuck to a rock. Calm sea gray.",
    dark: false,
    vars: {
      "--bg": "#e8ecec",
      "--bg-panel": "#dde3e3",
      "--bg-card": "#f4f7f7",
      "--bg-hover": "#d2dada",
      "--bg-active": "#c4cece",
      "--bg-msg": "#e0e6e6",
      "--border": "#c4cece",
      "--border2": "#b2bebe",
      "--border-input": "#9dacac",
      "--text": "#2b3a3e",
      "--text2": "#37474c",
      "--text3": "#48585e",
      "--text4": "#5c6c72",
      "--text5": "#728288",
      "--muted": "#88969a",
      "--accent": "#4a707a",
      "--accent2": "#2e4c58",
      "--success": "#3a7a52",
      "--success-border": "#a4c4ae",
      "--success-text": "#316644",
      "--danger": "#a83a3a",
      "--danger-text": "#a83a3a",
      "--warning": "#96700f",
      "--warning-border": "#d0c098",
      "--warning-text": "#6e5510",
      "--mono": "#2e6b4e",
      "--bubble-user": "#c2d2d8",
    },
  },
];
